name: XboxBurner

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-ubuntu-qt5:
    runs-on: ubuntu-latest
    steps:
      - name: install XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y qtbase5-dev dvd+rw-tools
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-macos-qt5:
    runs-on: 	macos-latest
    steps:
      - name: install XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: brew install qt@5  dvdrw-tools
      - name: run qmake
        run: qmake .
      - name: make
        run: make
