name: XboxBurner

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install XboxBurner
      run: sudo apt install -y qtbase5-dev dvd+rw-tools
      - name: make
      run: make
