name: XboxBurner

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-ubuntu-qt5:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y qtbase5-dev dvd+rw-tools
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-macos-qt5:
    runs-on: macos-latest
    steps:
      - name: MacOSX XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
         brew install qt@5 dvd+rw-tools
         brew link qt5 --force
         echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
         export LDFLAGS="-L/usr/local/opt/qt@5/lib"
         export CPPFLAGS="-I/usr/local/opt/qt@5/include"
         export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-macos-qt6:
    runs-on: 	macos-latest
    steps:
      - name: MacOSX XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
         brew install qt@6 dvd+rw-tools
         brew link qt6 --force
         echo 'export PATH="/usr/local/opt/qt@6/bin:$PATH"' >> /Users/runner/.bash_profile
         export LDFLAGS="-L/usr/local/opt/qt@6/lib"
         export CPPFLAGS="-I/usr/local/opt/qt@6/include"
         export PKG_CONFIG_PATH="/usr/local/opt/qt@6/lib/pkgconfig"
      - name: run qmake6
        run: qmake6 .
      - name: make
        run: make
  build-windows-qt5:
    runs-on: windows-latest
    steps:
      - name: Windows XboxBurner
        uses: actions/checkout@v2
      - name: Mingw64 Cache
        uses: actions/cache@v2.1.7
        id: mingw64-cache
        with:
          path: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin
          key: mingw64-bin
      - name: Qt5 Cache
        uses: actions/cache@v2.1.7
        id: qt5-bin-lib-cache
        with:
          path: C:\Qt\5.15.2\mingw81_64
          key: qt5-full-path
      - name: Install Mingw Compiler
        shell: pwsh
        if: steps.mingw64-cache.outputs.cache-hit != 'true'
        run: | 
         choco install mingw -y
      - name: Install Qt5
        shell: pwsh
        if: steps.qt5-bin-lib-cache.outputs.cache-hit != 'true'
        run: choco install qt5-default -y
      - name: XboxBurner Compilation
        shell: pwsh
        run: |
         $env:QTDIR = "C:\Qt\5.15.2\mingw81_64"
         $env:Path += ";C:\Qt\5.15.2\mingw81_64\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
         $env:QMAKESPEC = "C:\Qt\5.15.2\mingw81_64\mkspecs\win32-g++"
         qmake --version
         mingw32-make --version
         mkdir build-xboxburner
         cd build-xboxburner
         qmake ..
         mingw32-make

