name: XboxBurner

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-ubuntu-qt5:
    runs-on: ubuntu-latest
    steps:
      - name: install XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y qtbase5-dev dvd+rw-tools
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-macos-qt5:
    runs-on: 	macos-latest
    steps:
      - name: install XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
         brew install qt@5  dvd+rw-tools
         brew link qt5 --force
         echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
         export LDFLAGS="-L/usr/local/opt/qt@5/lib"
         export CPPFLAGS="-I/usr/local/opt/qt@5/include"
         export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-macos-qt6:
    runs-on: 	macos-latest
    steps:
      - name: install XboxBurner
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
         brew install qt@6 dvd+rw-tools
         brew link qt6 --force
         echo 'export PATH="/usr/local/opt/qt@6/bin:$PATH"' >> /Users/runner/.bash_profile
         export LDFLAGS="-L/usr/local/opt/qt@6/lib"
         export CPPFLAGS="-I/usr/local/opt/qt@6/include"
         export PKG_CONFIG_PATH="/usr/local/opt/qt@6/lib/pkgconfig"
      - name: run qmake
        run: qmake .
      - name: make
        run: make
  build-windows-qt5:
    runs-on: windows-latest
    steps:
      - name: Windows
        uses: actions/checkout@v2
      - name: Mingw32 Cache
        uses: actions/cache@v2.1.7
        id: mingw32-cache
        with:
          path: .\mingw-w64\mingw64\mingw64\bin
          key: mingw32-bin
      - name: Qt5 Cache
        uses: actions/cache@v2.1.7
        id: qt5-cache
        with:
          path: .\qtbase-everywhere-src-5.15.2\bin
          key: qt5-bin
      - name: Preparations
        shell: pwsh
        run: | 
         Invoke-Webrequest -Uri https://www.7-zip.org/a/7z2107-x64.msi -OutFile .\7z2107-x64.msi
         msiexec /i 7z2107-x64.msi /l*vx log.txt /quiet
         $env:Path += ";C:\Program Files\7-Zip"
         Invoke-Webrequest -Uri https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -OutFile .\mingw.7z
         mkdir .\mingw-w64\mingw64
         7z a -mx=9 mingw.7z .\mingw-w64\mingw64
      - name: Set Path for MingW32
        shell: pwsh
        run: $env:Path += ";.\mingw-w64\mingw64\mingw64\bin"
      - name: Download Qt5
        shell: pwsh
        env:
         QT5-CACHE-HIT: ${{steps.qt5-cache.outputs.cache-hit}}
        run: |
         & $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://platform.activestate.com/dl/cli/pdli01/install.ps1'))) -activate-default juliagoda/ActivePerl-5.28
         Invoke-Webrequest -Uri https://download.qt.io/archive/qt/5.15/5.15.2/submodules/qtbase-everywhere-src-5.15.2.zip -OutFile .\qtbase-everywhere-src-5.15.2.zip
         tar -xf qtbase-everywhere-src-5.15.2.zip
         cd qtbase-everywhere-src-5.15.2
         Invoke-Webrequest -Uri http://download.qt.io/official_releases/jom/jom.zip -OutFile .\jom.zip
         Expand-Archive jom.zip .
      - name: Qt5 Configuration
        shell: pwsh
        env:
         CACHE-HIT: ${{steps.qt5-cache.outputs.cache-hit}}
        run: |
         configure -confirm-license -platform win32-g++ -opensource -nomake tests -nomake examples -no-openvg -no-openssl -no-opengl -no-dbus
      - name: Build Qt5 Base 
        shell: pwsh
        env:
         CACHE-HIT: ${{steps.qt5-cache.outputs.cache-hit}}
        run: |
         mingw32-make
         cd .. 
      - name: Set Path for Qt5 Binaries
        shell: pwsh
        run: $env:Path += ";.\qtbase-everywhere-src-5.15.2\bin"
      - name: XboxBurner Compilation
        shell: pwsh
        run: |
         mkdir build-xboxburner
         cd build-xboxburner
         qmake ..
         mingw32-make
